# Generated by Django 5.1.6 on 2025-03-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='facility_name',
            field=models.CharField(default='Facility', max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='uni_name',
            field=models.CharField(default='Facility', max_length=50),
        ),
    ]
