# Generated by Django 5.1.6 on 2025-03-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_facility_name_account_uni_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='facility_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='uni_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
