# Generated by Django 5.1.6 on 2025-04-01 20:14

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_facility_name_alter_account_uni_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_joined',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_login',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
    ]
