# Generated by Django 5.1.2 on 2025-03-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_news_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='author',
        ),
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/News'),
        ),
    ]
