# Generated by Django 5.1.2 on 2025-03-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_new_author_alter_new_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30, verbose_name='نویسنده')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان مقاله')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('introduction', models.TextField(verbose_name='مقدمه')),
                ('body', models.TextField(verbose_name='متن مقاله')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='articles/images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='articles/images/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='articles/pdfs/', verbose_name='فایل PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='new',
            name='body',
            field=models.TextField(verbose_name='متن خبر'),
        ),
        migrations.AlterField(
            model_name='new',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار'),
        ),
        migrations.AlterField(
            model_name='new',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='new',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی'),
        ),
    ]
