# Generated by Django 5.1.2 on 2025-03-17 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_alter_new_body_alter_new_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'ordering': ['-created'], 'verbose_name': 'خبر', 'verbose_name_plural': 'اخبار'},
        ),
    ]
