# Generated by Django 5.1.6 on 2025-04-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='day',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='exam_day',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='exam_time',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='time',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='unit',
            field=models.IntegerField(),
        ),
    ]
