# Generated by Django 5.1.6 on 2025-04-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_course_delete_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='course_name',
        ),
        migrations.AlterField(
            model_name='course',
            name='days',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='units',
            field=models.IntegerField(),
        ),
    ]
